### ISSUE TITLE
Distribution version

### ISSUE THREAD

**Issue by Psychokrameur** [valeriangalliat/markdown-it-highlightjs#1]
Hello,

Can you please release a dist version?
(like in https://github.com/markdown-it/markdown-it-footnote, folder _dist_
This is an example of repo, but there is a lot of repo where you can find this)

Thanks a lot in advance

**Comment by valeriangalliat** [comment]
Hi @Psychokrameur,

The dist version is released on npm, when you `require('markdown-it-highlightjs')` it's actually the ES5-compiled version. Isn't it OK for you?

**Comment by Psychokrameur** [comment]
The think is... i did not use npm :)

**Comment by valeriangalliat** [comment]
You should use npm then, or you can run the prepublish script locally to compile the code if you don't want to use npm. 👍
