### ISSUE TITLE
Highlight.js Potential ReDOS vulnerabilities

### ISSUE THREAD

**Issue by angelaman** [valeriangalliat/markdown-it-highlightjs#16]
Hi guys,

I read [here](https://github.com/advisories/GHSA-7wwv-vh3v-89cq), highlight.js versions prior 10.4.1 are all vulnerable to potential ReDOS attacks. markdown-it-highlightjs currently depends on version `10.2.0`. Can you update it to version 10.4.1 instead? Thanks!

**Comment by valeriangalliat** [comment]
We depend on `^10.2.0` which means a `npm upgrade` will allow you to use further semver-compatible versions like 10.4.1 :)
