### ISSUE TITLE
Doesn't add `hljs` class to inline code

### ISSUE THREAD

**Issue by Maxim-Mazurok** [valeriangalliat/markdown-it-highlightjs#25]
I see this in most themes:
```css
code.hljs {
  padding: 3px 5px;
}
```

And I see similar thing for inline code on github:
```
.markdown-body code{
    padding: 0.2em 0.4em;
}
```

and on SO:
```
.s-prose *:not(.s-code-block)>code {
    padding: 2px 4px;
```

So I'm guessing that idea in highlights is that this padding is supposed to be added to inline code. But this class `hljs` is not being added :( Would be great to add it. Thanks!

**Comment by valeriangalliat** [comment]
Good catch! I think it's potentially breaking if people expected the `hljs` class to not be present, so I bumped a major, v4.0.0 (actually needs to be v4.0.1 because of a publish mistake) that now sets `hljs` on inline code class. Cheers :)
