### ISSUE TITLE
Heads up: upcoming changes in highlight.js break markdown-it-highlightjs

### ISSUE THREAD

**Issue by aral** [valeriangalliat/markdown-it-highlightjs#30]
I was successfully able to update highlight.js to the latest release version (11.9.0) – please see #29 – but not to the latest development build in main.

Details of the issue are in this issue on the highlight.js repository. If it’s not a regression but a breaking change in anticipation of a new major release, it might be something to plan ahead for:

https://github.com/highlightjs/highlight.js/issues/4026

**Comment by valeriangalliat** [comment]
I commented on the above issue, it seems related to installing from GitHub as opposed to from npm - the `lib` directory is part of the npm package but not part of the GitHub source which causes this error

I'm not worried about a breaking change in highlight.js otherwise!
