### ISSUE TITLE
How can I use a custom theme with the preset?

### ISSUE THREAD

**Issue by sabaimran** [valeriangalliat/markdown-it-highlightjs#31]
Hi! Thanks so much for making and maintaining this package. How can I use a custom theme with the package in a node project?

```typescript
import markdownIt from 'markdown-it';
import mditHljs from "markdown-it-highlightjs";

const md = new markdownIt({
    html: true,
    linkify: true,
    typographer: true
});

md.use(mditHljs, {
    inline: true,
    code: true
});
```

This is roughly what I have right now. It loads up the default theme, but I'd love to use something custom. Is the recommended way to do that just to use include a custom stylesheet, like [from here](https://unpkg.com/browse/highlightjs@9.16.2/styles/), and maybe manually [change the DOM](https://stackoverflow.com/questions/77708074/how-to-toggle-between-light-theme-and-dark-theme-in-highlightjs) references?

**Comment by valeriangalliat** [comment]
Hi! Yeah in my experience customizing the theme is done by switching the stylesheet :) I'm not aware of there being any markup change between different themes

**Comment by sabaimran** [comment]
Got it! For anyone else encountering this issue in Next/React, this is how I ended up doing it: https://github.com/khoj-ai/khoj/blob/405c047c0ccc2e082f562799263556dfcf70f7fb/src/interface/web/app/globals.css#L45

I manually included the relevant stylesheet in my `globals.css` and had it switch when using the `.dark` class.
