### ISSUE TITLE
License

### ISSUE THREAD

**Issue by char0n** [valeriangalliat/markdown-it-highlightjs#5]
Hi, nice work on this lib. I am just wondering: will you be willing to adopt an [MIT](https://opensource.org/licenses/MIT) or any other opensource license for this project ? It is very hard to use unlicensed software in corporate environment. I assume by releasing it as UNLICENSED you meant only good things and let people use the lib any way they like. But the result is just opposite and without the explicit license it will not be possible to use in any commercial products.

Sorry for longer description, and looking forward to your answer.

**Comment by valeriangalliat** [comment]
Hey! Thanks for asking. :)

The [Unlicence](http://unlicense.org/) is [present in this project](https://github.com/valeriangalliat/markdown-it-highlightjs/blob/master/UNLICENSE) to explicitly and legally put it in the public domain.

It's different from a project which would not have any licensing statement at all (where you're totally right, would be tricky to use in other projects).

After checking the http://unlicense.org/ website and the terms of the [present license](https://github.com/valeriangalliat/markdown-it-highlightjs/blob/master/UNLICENSE) is it still a problem for you to use this project?

**Comment by char0n** [comment]
Sorry did non notice the `UNLICENSE` in the repo, I was looking for LICENSE.md file. UNLICENSE explicit license is totally ok with corporate usage. Thank you and have a nice day ;]

**Comment by valeriangalliat** [comment]
Amazing, enjoy! :)
